name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Prepare k3s offline package
      run: |
        bash prepare_airgap_installer/download_package.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          k3s_offline_*.tar.gz

  test_download:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
    - name: Download from github release
      run: |
        rm *.tar.gz
        ls -lah
        wget -q https://github.com/ren15/k3s_deployment/releases/download/latest/k3s_offline_v1.23.4+k3s1.tar.gz
        tar xvf k3s_offline_v1.23.4+k3s1.tar.gz
        ls -lah
        ls -lah k3s*
